---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# onsvtables

<!-- badges: start -->
<!-- badges: end -->

`onsvtables` is a package that provides a function for customizing `gt` tables with the [National Road Safety Observatory (ONSV)](https://www.onsv.org.br/) style.

## Installation

You can install the development version of `onsvtables` from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ONSV/onsvtables")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(onsvtables)

df <- data.frame(
  var1 = c("lorem", "ipsum", "dolor"),
  var2 = c(1, 2, 3)
)

tbl_onsv <-
  df |>
  gt::gt() |>
  tab_onsv()
```

### Citation

This package can be cited as follows:

```{r}
citation("onsvtables")
```

